### ISSUE TITLE
#layers required for GCN explainability 

### ISSUE THREAD

**Issue by abhigoku10** [ndey96/GCNN-Explainability#4]
@ndey96  can this be applied to 3 layer gcn architecture with global pool ?? can we have two layer architecture before providing it to softmax function ?

**Comment by nolan-cerebras** [comment]
Hi @abhigoku10 in [models.py](https://github.com/ndey96/GCNN-Explainability/blob/master/models.py) the model defined is a 3 layer GCNN, followed by global average pooling and a fully-connected output layer. If you would like to have a two layer architecture you can easily modify this file to do so :) Let me know if you have any questions
