### ISSUE TITLE
question in explain.py

### ISSUE THREAD

**Issue by Walker-ZD** [ndey96/GCNN-Explainability#5]
Thanks for your sharing. Now I have a question in code:
https://github.com/ndey96/GCNN-Explainability/blob/7571e72fef3efdf7a0954ed5adf774724159d2fd/explain.py#L100
Shape of input_grads is 40 * 8. 40 is the number of nodes and 8 is features for every node. So, why this place is shape[1]? If we loop n nodes, I think this place should be shape[0].

**Comment by nolan-cerebras** [comment]
Thanks for catching that bug! I will update `explain.py`

**Comment by nolan-cerebras** [comment]
Done in 5c20f4f51fa697dd2ccb453f83b7c6872227e9f7
